

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "67", "78", "79", "80", "81"],
		"CDFG" : "systolic_array_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "272", "EstimateLatencyMax" : "272",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_systolic_array_kernel_Pipeline_CYCLE_fu_358", "Port" : "gmem0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_systolic_array_kernel_Pipeline_CYCLE_fu_358", "Port" : "gmem1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434", "Port" : "gmem2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "A", "Type" : "None", "Direction" : "I"},
			{"Name" : "B", "Type" : "None", "Direction" : "I"},
			{"Name" : "C", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66"],
		"CDFG" : "systolic_array_kernel_Pipeline_CYCLE",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "196", "EstimateLatencyMax" : "196",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "A", "Type" : "None", "Direction" : "I"},
			{"Name" : "B", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_7465_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_6462_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_5459_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_4456_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_3453_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_2450_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7_1447_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7444_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_7442_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_6439_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_5436_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_4433_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_3430_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_2427_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6_1424_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6421_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_7419_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_6416_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_5413_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_4410_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_3407_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_2404_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5_1401_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5398_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_7396_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_6393_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_5390_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_4387_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_3384_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_2381_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4_1378_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4375_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_7373_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_6370_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_5367_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_4364_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_3361_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_2358_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3_1355_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3352_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_7350_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_6347_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_5344_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_4341_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_3338_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_2335_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2_1332_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2329_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_7327_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_6324_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_5321_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_4318_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_3315_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_2312_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1_1309_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1306_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_7219304_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_6209302_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_5199300_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_4189298_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_3179296_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_2169294_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i_1159292_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "conv3_i_i290_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "CYCLE", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "8", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage3", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage3_subdone", "QuitState" : "ap_ST_fsm_pp0_stage3", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage3_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U6", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U7", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U8", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U9", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U10", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U11", "Parent" : "1"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U12", "Parent" : "1"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U13", "Parent" : "1"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U14", "Parent" : "1"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U15", "Parent" : "1"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U16", "Parent" : "1"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U17", "Parent" : "1"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U18", "Parent" : "1"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U19", "Parent" : "1"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U20", "Parent" : "1"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U21", "Parent" : "1"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U22", "Parent" : "1"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U23", "Parent" : "1"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U24", "Parent" : "1"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U25", "Parent" : "1"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U26", "Parent" : "1"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U27", "Parent" : "1"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U28", "Parent" : "1"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U29", "Parent" : "1"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U30", "Parent" : "1"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U31", "Parent" : "1"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U32", "Parent" : "1"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U33", "Parent" : "1"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U34", "Parent" : "1"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U35", "Parent" : "1"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U36", "Parent" : "1"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U37", "Parent" : "1"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U38", "Parent" : "1"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U39", "Parent" : "1"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U40", "Parent" : "1"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U41", "Parent" : "1"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U42", "Parent" : "1"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U43", "Parent" : "1"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U44", "Parent" : "1"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U45", "Parent" : "1"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U46", "Parent" : "1"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U47", "Parent" : "1"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U48", "Parent" : "1"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U49", "Parent" : "1"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U50", "Parent" : "1"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U51", "Parent" : "1"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U52", "Parent" : "1"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U53", "Parent" : "1"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U54", "Parent" : "1"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U55", "Parent" : "1"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U56", "Parent" : "1"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U57", "Parent" : "1"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U58", "Parent" : "1"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U59", "Parent" : "1"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U60", "Parent" : "1"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U61", "Parent" : "1"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U62", "Parent" : "1"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U63", "Parent" : "1"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.mac_muladd_16s_16s_16ns_16_4_1_U64", "Parent" : "1"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_CYCLE_fu_358.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "67", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434", "Parent" : "0", "Child" : ["68", "69", "70", "71", "72", "73", "74", "75", "76", "77"],
		"CDFG" : "systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "68", "EstimateLatencyMax" : "68",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln160", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i290_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1159292_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2169294_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3179296_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4189298_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5199300_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6209302_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7219304_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1306_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_1309_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_2312_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_3315_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_4318_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_5321_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_6324_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_1_7327_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2329_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_1332_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_2335_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_3338_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_4341_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_5344_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_6347_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_2_7350_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3352_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_1355_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_2358_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_3361_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_4364_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_5367_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_6370_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_3_7373_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4375_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_1378_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_2381_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_3384_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_4387_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_5390_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_6393_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_4_7396_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5398_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_1401_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_2404_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_3407_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_4410_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_5413_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_6416_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_5_7419_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6421_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_1424_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_2427_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_3430_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_4433_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_5436_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_6439_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_6_7442_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7444_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_1447_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_2450_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_3453_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_4456_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_5459_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_6462_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_i_i_7_7465_reload", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "EXTRACT_I_EXTRACT_J", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U134", "Parent" : "67"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U135", "Parent" : "67"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U136", "Parent" : "67"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U137", "Parent" : "67"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U138", "Parent" : "67"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U139", "Parent" : "67"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U140", "Parent" : "67"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U141", "Parent" : "67"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.sparsemux_17_3_16_1_1_U142", "Parent" : "67"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J_fu_434.flow_control_loop_pipe_sequential_init_U", "Parent" : "67"},
	{"ID" : "78", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"}]}
