// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module systolic_array_kernel_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        sext_ln160,
        conv3_i_i290_reload,
        conv3_i_i_1159292_reload,
        conv3_i_i_2169294_reload,
        conv3_i_i_3179296_reload,
        conv3_i_i_4189298_reload,
        conv3_i_i_5199300_reload,
        conv3_i_i_6209302_reload,
        conv3_i_i_7219304_reload,
        conv3_i_i_1306_reload,
        conv3_i_i_1_1309_reload,
        conv3_i_i_1_2312_reload,
        conv3_i_i_1_3315_reload,
        conv3_i_i_1_4318_reload,
        conv3_i_i_1_5321_reload,
        conv3_i_i_1_6324_reload,
        conv3_i_i_1_7327_reload,
        conv3_i_i_2329_reload,
        conv3_i_i_2_1332_reload,
        conv3_i_i_2_2335_reload,
        conv3_i_i_2_3338_reload,
        conv3_i_i_2_4341_reload,
        conv3_i_i_2_5344_reload,
        conv3_i_i_2_6347_reload,
        conv3_i_i_2_7350_reload,
        conv3_i_i_3352_reload,
        conv3_i_i_3_1355_reload,
        conv3_i_i_3_2358_reload,
        conv3_i_i_3_3361_reload,
        conv3_i_i_3_4364_reload,
        conv3_i_i_3_5367_reload,
        conv3_i_i_3_6370_reload,
        conv3_i_i_3_7373_reload,
        conv3_i_i_4375_reload,
        conv3_i_i_4_1378_reload,
        conv3_i_i_4_2381_reload,
        conv3_i_i_4_3384_reload,
        conv3_i_i_4_4387_reload,
        conv3_i_i_4_5390_reload,
        conv3_i_i_4_6393_reload,
        conv3_i_i_4_7396_reload,
        conv3_i_i_5398_reload,
        conv3_i_i_5_1401_reload,
        conv3_i_i_5_2404_reload,
        conv3_i_i_5_3407_reload,
        conv3_i_i_5_4410_reload,
        conv3_i_i_5_5413_reload,
        conv3_i_i_5_6416_reload,
        conv3_i_i_5_7419_reload,
        conv3_i_i_6421_reload,
        conv3_i_i_6_1424_reload,
        conv3_i_i_6_2427_reload,
        conv3_i_i_6_3430_reload,
        conv3_i_i_6_4433_reload,
        conv3_i_i_6_5436_reload,
        conv3_i_i_6_6439_reload,
        conv3_i_i_6_7442_reload,
        conv3_i_i_7444_reload,
        conv3_i_i_7_1447_reload,
        conv3_i_i_7_2450_reload,
        conv3_i_i_7_3453_reload,
        conv3_i_i_7_4456_reload,
        conv3_i_i_7_5459_reload,
        conv3_i_i_7_6462_reload,
        conv3_i_i_7_7465_reload
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [15:0] m_axi_gmem2_0_WDATA;
output  [1:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [15:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [9:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [62:0] sext_ln160;
input  [15:0] conv3_i_i290_reload;
input  [15:0] conv3_i_i_1159292_reload;
input  [15:0] conv3_i_i_2169294_reload;
input  [15:0] conv3_i_i_3179296_reload;
input  [15:0] conv3_i_i_4189298_reload;
input  [15:0] conv3_i_i_5199300_reload;
input  [15:0] conv3_i_i_6209302_reload;
input  [15:0] conv3_i_i_7219304_reload;
input  [15:0] conv3_i_i_1306_reload;
input  [15:0] conv3_i_i_1_1309_reload;
input  [15:0] conv3_i_i_1_2312_reload;
input  [15:0] conv3_i_i_1_3315_reload;
input  [15:0] conv3_i_i_1_4318_reload;
input  [15:0] conv3_i_i_1_5321_reload;
input  [15:0] conv3_i_i_1_6324_reload;
input  [15:0] conv3_i_i_1_7327_reload;
input  [15:0] conv3_i_i_2329_reload;
input  [15:0] conv3_i_i_2_1332_reload;
input  [15:0] conv3_i_i_2_2335_reload;
input  [15:0] conv3_i_i_2_3338_reload;
input  [15:0] conv3_i_i_2_4341_reload;
input  [15:0] conv3_i_i_2_5344_reload;
input  [15:0] conv3_i_i_2_6347_reload;
input  [15:0] conv3_i_i_2_7350_reload;
input  [15:0] conv3_i_i_3352_reload;
input  [15:0] conv3_i_i_3_1355_reload;
input  [15:0] conv3_i_i_3_2358_reload;
input  [15:0] conv3_i_i_3_3361_reload;
input  [15:0] conv3_i_i_3_4364_reload;
input  [15:0] conv3_i_i_3_5367_reload;
input  [15:0] conv3_i_i_3_6370_reload;
input  [15:0] conv3_i_i_3_7373_reload;
input  [15:0] conv3_i_i_4375_reload;
input  [15:0] conv3_i_i_4_1378_reload;
input  [15:0] conv3_i_i_4_2381_reload;
input  [15:0] conv3_i_i_4_3384_reload;
input  [15:0] conv3_i_i_4_4387_reload;
input  [15:0] conv3_i_i_4_5390_reload;
input  [15:0] conv3_i_i_4_6393_reload;
input  [15:0] conv3_i_i_4_7396_reload;
input  [15:0] conv3_i_i_5398_reload;
input  [15:0] conv3_i_i_5_1401_reload;
input  [15:0] conv3_i_i_5_2404_reload;
input  [15:0] conv3_i_i_5_3407_reload;
input  [15:0] conv3_i_i_5_4410_reload;
input  [15:0] conv3_i_i_5_5413_reload;
input  [15:0] conv3_i_i_5_6416_reload;
input  [15:0] conv3_i_i_5_7419_reload;
input  [15:0] conv3_i_i_6421_reload;
input  [15:0] conv3_i_i_6_1424_reload;
input  [15:0] conv3_i_i_6_2427_reload;
input  [15:0] conv3_i_i_6_3430_reload;
input  [15:0] conv3_i_i_6_4433_reload;
input  [15:0] conv3_i_i_6_5436_reload;
input  [15:0] conv3_i_i_6_6439_reload;
input  [15:0] conv3_i_i_6_7442_reload;
input  [15:0] conv3_i_i_7444_reload;
input  [15:0] conv3_i_i_7_1447_reload;
input  [15:0] conv3_i_i_7_2450_reload;
input  [15:0] conv3_i_i_7_3453_reload;
input  [15:0] conv3_i_i_7_4456_reload;
input  [15:0] conv3_i_i_7_5459_reload;
input  [15:0] conv3_i_i_7_6462_reload;
input  [15:0] conv3_i_i_7_7465_reload;

reg ap_idle;
reg m_axi_gmem2_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln160_fu_634_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem2_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln161_fu_654_p2;
reg   [0:0] icmp_ln161_reg_1352;
wire   [15:0] tmp_fu_672_p19;
reg   [15:0] tmp_reg_1357;
wire   [15:0] tmp_1_fu_704_p19;
reg   [15:0] tmp_1_reg_1362;
wire   [15:0] tmp_2_fu_736_p19;
reg   [15:0] tmp_2_reg_1367;
wire   [15:0] tmp_3_fu_768_p19;
reg   [15:0] tmp_3_reg_1372;
wire   [15:0] tmp_4_fu_800_p19;
reg   [15:0] tmp_4_reg_1377;
wire   [15:0] tmp_5_fu_832_p19;
reg   [15:0] tmp_5_reg_1382;
wire   [15:0] tmp_6_fu_864_p19;
reg   [15:0] tmp_6_reg_1387;
wire   [15:0] tmp_7_fu_896_p19;
reg   [15:0] tmp_7_reg_1392;
wire   [15:0] tmp_8_fu_959_p19;
reg   [15:0] tmp_8_reg_1397;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [3:0] j_fu_202;
wire   [3:0] add_ln161_fu_928_p2;
wire    ap_loop_init;
reg   [3:0] i_fu_206;
wire   [3:0] select_ln160_1_fu_948_p3;
reg   [6:0] indvar_flatten_fu_210;
wire   [6:0] add_ln160_fu_640_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
wire   [3:0] select_ln160_fu_660_p3;
wire   [15:0] tmp_fu_672_p17;
wire   [2:0] trunc_ln161_fu_668_p1;
wire   [15:0] tmp_1_fu_704_p17;
wire   [15:0] tmp_2_fu_736_p17;
wire   [15:0] tmp_3_fu_768_p17;
wire   [15:0] tmp_4_fu_800_p17;
wire   [15:0] tmp_5_fu_832_p17;
wire   [15:0] tmp_6_fu_864_p17;
wire   [15:0] tmp_7_fu_896_p17;
wire   [3:0] add_ln160_1_fu_942_p2;
wire   [15:0] tmp_8_fu_959_p17;
wire   [2:0] tmp_8_fu_959_p18;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_672_p1;
wire   [2:0] tmp_fu_672_p3;
wire   [2:0] tmp_fu_672_p5;
wire   [2:0] tmp_fu_672_p7;
wire  signed [2:0] tmp_fu_672_p9;
wire  signed [2:0] tmp_fu_672_p11;
wire  signed [2:0] tmp_fu_672_p13;
wire  signed [2:0] tmp_fu_672_p15;
wire   [2:0] tmp_1_fu_704_p1;
wire   [2:0] tmp_1_fu_704_p3;
wire   [2:0] tmp_1_fu_704_p5;
wire   [2:0] tmp_1_fu_704_p7;
wire  signed [2:0] tmp_1_fu_704_p9;
wire  signed [2:0] tmp_1_fu_704_p11;
wire  signed [2:0] tmp_1_fu_704_p13;
wire  signed [2:0] tmp_1_fu_704_p15;
wire   [2:0] tmp_2_fu_736_p1;
wire   [2:0] tmp_2_fu_736_p3;
wire   [2:0] tmp_2_fu_736_p5;
wire   [2:0] tmp_2_fu_736_p7;
wire  signed [2:0] tmp_2_fu_736_p9;
wire  signed [2:0] tmp_2_fu_736_p11;
wire  signed [2:0] tmp_2_fu_736_p13;
wire  signed [2:0] tmp_2_fu_736_p15;
wire   [2:0] tmp_3_fu_768_p1;
wire   [2:0] tmp_3_fu_768_p3;
wire   [2:0] tmp_3_fu_768_p5;
wire   [2:0] tmp_3_fu_768_p7;
wire  signed [2:0] tmp_3_fu_768_p9;
wire  signed [2:0] tmp_3_fu_768_p11;
wire  signed [2:0] tmp_3_fu_768_p13;
wire  signed [2:0] tmp_3_fu_768_p15;
wire   [2:0] tmp_4_fu_800_p1;
wire   [2:0] tmp_4_fu_800_p3;
wire   [2:0] tmp_4_fu_800_p5;
wire   [2:0] tmp_4_fu_800_p7;
wire  signed [2:0] tmp_4_fu_800_p9;
wire  signed [2:0] tmp_4_fu_800_p11;
wire  signed [2:0] tmp_4_fu_800_p13;
wire  signed [2:0] tmp_4_fu_800_p15;
wire   [2:0] tmp_5_fu_832_p1;
wire   [2:0] tmp_5_fu_832_p3;
wire   [2:0] tmp_5_fu_832_p5;
wire   [2:0] tmp_5_fu_832_p7;
wire  signed [2:0] tmp_5_fu_832_p9;
wire  signed [2:0] tmp_5_fu_832_p11;
wire  signed [2:0] tmp_5_fu_832_p13;
wire  signed [2:0] tmp_5_fu_832_p15;
wire   [2:0] tmp_6_fu_864_p1;
wire   [2:0] tmp_6_fu_864_p3;
wire   [2:0] tmp_6_fu_864_p5;
wire   [2:0] tmp_6_fu_864_p7;
wire  signed [2:0] tmp_6_fu_864_p9;
wire  signed [2:0] tmp_6_fu_864_p11;
wire  signed [2:0] tmp_6_fu_864_p13;
wire  signed [2:0] tmp_6_fu_864_p15;
wire   [2:0] tmp_7_fu_896_p1;
wire   [2:0] tmp_7_fu_896_p3;
wire   [2:0] tmp_7_fu_896_p5;
wire   [2:0] tmp_7_fu_896_p7;
wire  signed [2:0] tmp_7_fu_896_p9;
wire  signed [2:0] tmp_7_fu_896_p11;
wire  signed [2:0] tmp_7_fu_896_p13;
wire  signed [2:0] tmp_7_fu_896_p15;
wire   [2:0] tmp_8_fu_959_p1;
wire   [2:0] tmp_8_fu_959_p3;
wire   [2:0] tmp_8_fu_959_p5;
wire   [2:0] tmp_8_fu_959_p7;
wire  signed [2:0] tmp_8_fu_959_p9;
wire  signed [2:0] tmp_8_fu_959_p11;
wire  signed [2:0] tmp_8_fu_959_p13;
wire  signed [2:0] tmp_8_fu_959_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_202 = 4'd0;
#0 i_fu_206 = 4'd0;
#0 indvar_flatten_fu_210 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U134(
    .din0(conv3_i_i290_reload),
    .din1(conv3_i_i_1159292_reload),
    .din2(conv3_i_i_2169294_reload),
    .din3(conv3_i_i_3179296_reload),
    .din4(conv3_i_i_4189298_reload),
    .din5(conv3_i_i_5199300_reload),
    .din6(conv3_i_i_6209302_reload),
    .din7(conv3_i_i_7219304_reload),
    .def(tmp_fu_672_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_fu_672_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U135(
    .din0(conv3_i_i_1306_reload),
    .din1(conv3_i_i_1_1309_reload),
    .din2(conv3_i_i_1_2312_reload),
    .din3(conv3_i_i_1_3315_reload),
    .din4(conv3_i_i_1_4318_reload),
    .din5(conv3_i_i_1_5321_reload),
    .din6(conv3_i_i_1_6324_reload),
    .din7(conv3_i_i_1_7327_reload),
    .def(tmp_1_fu_704_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_1_fu_704_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U136(
    .din0(conv3_i_i_2329_reload),
    .din1(conv3_i_i_2_1332_reload),
    .din2(conv3_i_i_2_2335_reload),
    .din3(conv3_i_i_2_3338_reload),
    .din4(conv3_i_i_2_4341_reload),
    .din5(conv3_i_i_2_5344_reload),
    .din6(conv3_i_i_2_6347_reload),
    .din7(conv3_i_i_2_7350_reload),
    .def(tmp_2_fu_736_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_2_fu_736_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U137(
    .din0(conv3_i_i_3352_reload),
    .din1(conv3_i_i_3_1355_reload),
    .din2(conv3_i_i_3_2358_reload),
    .din3(conv3_i_i_3_3361_reload),
    .din4(conv3_i_i_3_4364_reload),
    .din5(conv3_i_i_3_5367_reload),
    .din6(conv3_i_i_3_6370_reload),
    .din7(conv3_i_i_3_7373_reload),
    .def(tmp_3_fu_768_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_3_fu_768_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U138(
    .din0(conv3_i_i_4375_reload),
    .din1(conv3_i_i_4_1378_reload),
    .din2(conv3_i_i_4_2381_reload),
    .din3(conv3_i_i_4_3384_reload),
    .din4(conv3_i_i_4_4387_reload),
    .din5(conv3_i_i_4_5390_reload),
    .din6(conv3_i_i_4_6393_reload),
    .din7(conv3_i_i_4_7396_reload),
    .def(tmp_4_fu_800_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_4_fu_800_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U139(
    .din0(conv3_i_i_5398_reload),
    .din1(conv3_i_i_5_1401_reload),
    .din2(conv3_i_i_5_2404_reload),
    .din3(conv3_i_i_5_3407_reload),
    .din4(conv3_i_i_5_4410_reload),
    .din5(conv3_i_i_5_5413_reload),
    .din6(conv3_i_i_5_6416_reload),
    .din7(conv3_i_i_5_7419_reload),
    .def(tmp_5_fu_832_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_5_fu_832_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U140(
    .din0(conv3_i_i_6421_reload),
    .din1(conv3_i_i_6_1424_reload),
    .din2(conv3_i_i_6_2427_reload),
    .din3(conv3_i_i_6_3430_reload),
    .din4(conv3_i_i_6_4433_reload),
    .din5(conv3_i_i_6_5436_reload),
    .din6(conv3_i_i_6_6439_reload),
    .din7(conv3_i_i_6_7442_reload),
    .def(tmp_6_fu_864_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_6_fu_864_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U141(
    .din0(conv3_i_i_7444_reload),
    .din1(conv3_i_i_7_1447_reload),
    .din2(conv3_i_i_7_2450_reload),
    .din3(conv3_i_i_7_3453_reload),
    .din4(conv3_i_i_7_4456_reload),
    .din5(conv3_i_i_7_5459_reload),
    .din6(conv3_i_i_7_6462_reload),
    .din7(conv3_i_i_7_7465_reload),
    .def(tmp_7_fu_896_p17),
    .sel(trunc_ln161_fu_668_p1),
    .dout(tmp_7_fu_896_p19)
);

(* dissolve_hierarchy = "yes" *) systolic_array_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U142(
    .din0(tmp_reg_1357),
    .din1(tmp_1_reg_1362),
    .din2(tmp_2_reg_1367),
    .din3(tmp_3_reg_1372),
    .din4(tmp_4_reg_1377),
    .din5(tmp_5_reg_1382),
    .din6(tmp_6_reg_1387),
    .din7(tmp_7_reg_1392),
    .def(tmp_8_fu_959_p17),
    .sel(tmp_8_fu_959_p18),
    .dout(tmp_8_fu_959_p19)
);

systolic_array_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_fu_206 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_206 <= select_ln160_1_fu_948_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln160_fu_634_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_210 <= add_ln160_fu_640_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_210 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_202 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_202 <= add_ln161_fu_928_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln161_reg_1352 <= icmp_ln161_fu_654_p2;
        tmp_1_reg_1362 <= tmp_1_fu_704_p19;
        tmp_2_reg_1367 <= tmp_2_fu_736_p19;
        tmp_3_reg_1372 <= tmp_3_fu_768_p19;
        tmp_4_reg_1377 <= tmp_4_fu_800_p19;
        tmp_5_reg_1382 <= tmp_5_fu_832_p19;
        tmp_6_reg_1387 <= tmp_6_fu_864_p19;
        tmp_7_reg_1392 <= tmp_7_fu_896_p19;
        tmp_reg_1357 <= tmp_fu_672_p19;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        tmp_8_reg_1397 <= tmp_8_fu_959_p19;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_634_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        gmem2_blk_n_W = m_axi_gmem2_0_WREADY;
    end else begin
        gmem2_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        m_axi_gmem2_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem2_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_1_fu_942_p2 = (i_fu_206 + 4'd1);

assign add_ln160_fu_640_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln161_fu_928_p2 = (select_ln160_fu_660_p3 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln160_fu_634_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_654_p2 = ((j_fu_202 == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem2_0_ARADDR = 64'd0;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 32'd0;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_ARVALID = 1'b0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_RREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = tmp_8_reg_1397;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 2'd3;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign select_ln160_1_fu_948_p3 = ((icmp_ln161_reg_1352[0:0] == 1'b1) ? add_ln160_1_fu_942_p2 : i_fu_206);

assign select_ln160_fu_660_p3 = ((icmp_ln161_fu_654_p2[0:0] == 1'b1) ? 4'd0 : j_fu_202);

assign tmp_1_fu_704_p17 = 'bx;

assign tmp_2_fu_736_p17 = 'bx;

assign tmp_3_fu_768_p17 = 'bx;

assign tmp_4_fu_800_p17 = 'bx;

assign tmp_5_fu_832_p17 = 'bx;

assign tmp_6_fu_864_p17 = 'bx;

assign tmp_7_fu_896_p17 = 'bx;

assign tmp_8_fu_959_p17 = 'bx;

assign tmp_8_fu_959_p18 = select_ln160_1_fu_948_p3[2:0];

assign tmp_fu_672_p17 = 'bx;

assign trunc_ln161_fu_668_p1 = select_ln160_fu_660_p3[2:0];

endmodule //systolic_array_kernel_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J
