-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity systolic_array_kernel_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln160 : IN STD_LOGIC_VECTOR (62 downto 0);
    conv3_i_i290_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1159292_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2169294_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3179296_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4189298_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5199300_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6209302_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7219304_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1306_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_1309_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_2312_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_3315_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_4318_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_5321_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_6324_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_1_7327_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2329_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_1332_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_2335_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_3338_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_4341_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_5344_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_6347_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_2_7350_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3352_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_1355_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_2358_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_3361_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_4364_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_5367_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_6370_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_3_7373_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4375_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_1378_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_2381_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_3384_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_4387_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_5390_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_6393_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_4_7396_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5398_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_1401_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_2404_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_3407_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_4410_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_5413_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_6416_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_5_7419_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6421_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_1424_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_2427_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_3430_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_4433_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_5436_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_6439_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_6_7442_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7444_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_1447_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_2450_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_3453_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_4456_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_5459_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_6462_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    conv3_i_i_7_7465_reload : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of systolic_array_kernel_systolic_array_kernel_Pipeline_EXTRACT_I_EXTRACT_J is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln160_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln161_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln161_reg_1352 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_672_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1357 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_704_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_reg_1362 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_736_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_reg_1367 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_768_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_reg_1372 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_800_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_1377 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_832_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_reg_1382 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_864_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_1387 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_896_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_reg_1392 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_959_p19 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_reg_1397 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal j_fu_202 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln161_fu_928_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_206 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln160_1_fu_948_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_210 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln160_fu_640_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal select_ln160_fu_660_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_672_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln161_fu_668_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_736_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_768_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_800_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_832_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_864_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_896_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln160_1_fu_942_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_959_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_959_p18 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_672_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_672_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_704_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_736_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_768_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_800_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_832_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_864_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_896_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_959_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component systolic_array_kernel_sparsemux_17_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component systolic_array_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_16_1_1_U134 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i290_reload,
        din1 => conv3_i_i_1159292_reload,
        din2 => conv3_i_i_2169294_reload,
        din3 => conv3_i_i_3179296_reload,
        din4 => conv3_i_i_4189298_reload,
        din5 => conv3_i_i_5199300_reload,
        din6 => conv3_i_i_6209302_reload,
        din7 => conv3_i_i_7219304_reload,
        def => tmp_fu_672_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_fu_672_p19);

    sparsemux_17_3_16_1_1_U135 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_1306_reload,
        din1 => conv3_i_i_1_1309_reload,
        din2 => conv3_i_i_1_2312_reload,
        din3 => conv3_i_i_1_3315_reload,
        din4 => conv3_i_i_1_4318_reload,
        din5 => conv3_i_i_1_5321_reload,
        din6 => conv3_i_i_1_6324_reload,
        din7 => conv3_i_i_1_7327_reload,
        def => tmp_1_fu_704_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_1_fu_704_p19);

    sparsemux_17_3_16_1_1_U136 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_2329_reload,
        din1 => conv3_i_i_2_1332_reload,
        din2 => conv3_i_i_2_2335_reload,
        din3 => conv3_i_i_2_3338_reload,
        din4 => conv3_i_i_2_4341_reload,
        din5 => conv3_i_i_2_5344_reload,
        din6 => conv3_i_i_2_6347_reload,
        din7 => conv3_i_i_2_7350_reload,
        def => tmp_2_fu_736_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_2_fu_736_p19);

    sparsemux_17_3_16_1_1_U137 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_3352_reload,
        din1 => conv3_i_i_3_1355_reload,
        din2 => conv3_i_i_3_2358_reload,
        din3 => conv3_i_i_3_3361_reload,
        din4 => conv3_i_i_3_4364_reload,
        din5 => conv3_i_i_3_5367_reload,
        din6 => conv3_i_i_3_6370_reload,
        din7 => conv3_i_i_3_7373_reload,
        def => tmp_3_fu_768_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_3_fu_768_p19);

    sparsemux_17_3_16_1_1_U138 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_4375_reload,
        din1 => conv3_i_i_4_1378_reload,
        din2 => conv3_i_i_4_2381_reload,
        din3 => conv3_i_i_4_3384_reload,
        din4 => conv3_i_i_4_4387_reload,
        din5 => conv3_i_i_4_5390_reload,
        din6 => conv3_i_i_4_6393_reload,
        din7 => conv3_i_i_4_7396_reload,
        def => tmp_4_fu_800_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_4_fu_800_p19);

    sparsemux_17_3_16_1_1_U139 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_5398_reload,
        din1 => conv3_i_i_5_1401_reload,
        din2 => conv3_i_i_5_2404_reload,
        din3 => conv3_i_i_5_3407_reload,
        din4 => conv3_i_i_5_4410_reload,
        din5 => conv3_i_i_5_5413_reload,
        din6 => conv3_i_i_5_6416_reload,
        din7 => conv3_i_i_5_7419_reload,
        def => tmp_5_fu_832_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_5_fu_832_p19);

    sparsemux_17_3_16_1_1_U140 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_6421_reload,
        din1 => conv3_i_i_6_1424_reload,
        din2 => conv3_i_i_6_2427_reload,
        din3 => conv3_i_i_6_3430_reload,
        din4 => conv3_i_i_6_4433_reload,
        din5 => conv3_i_i_6_5436_reload,
        din6 => conv3_i_i_6_6439_reload,
        din7 => conv3_i_i_6_7442_reload,
        def => tmp_6_fu_864_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_6_fu_864_p19);

    sparsemux_17_3_16_1_1_U141 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => conv3_i_i_7444_reload,
        din1 => conv3_i_i_7_1447_reload,
        din2 => conv3_i_i_7_2450_reload,
        din3 => conv3_i_i_7_3453_reload,
        din4 => conv3_i_i_7_4456_reload,
        din5 => conv3_i_i_7_5459_reload,
        din6 => conv3_i_i_7_6462_reload,
        din7 => conv3_i_i_7_7465_reload,
        def => tmp_7_fu_896_p17,
        sel => trunc_ln161_fu_668_p1,
        dout => tmp_7_fu_896_p19);

    sparsemux_17_3_16_1_1_U142 : component systolic_array_kernel_sparsemux_17_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        CASE4 => "100",
        din4_WIDTH => 16,
        CASE5 => "101",
        din5_WIDTH => 16,
        CASE6 => "110",
        din6_WIDTH => 16,
        CASE7 => "111",
        din7_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_reg_1357,
        din1 => tmp_1_reg_1362,
        din2 => tmp_2_reg_1367,
        din3 => tmp_3_reg_1372,
        din4 => tmp_4_reg_1377,
        din5 => tmp_5_reg_1382,
        din6 => tmp_6_reg_1387,
        din7 => tmp_7_reg_1392,
        def => tmp_8_fu_959_p17,
        sel => tmp_8_fu_959_p18,
        dout => tmp_8_fu_959_p19);

    flow_control_loop_pipe_sequential_init_U : component systolic_array_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    i_fu_206 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_206 <= select_ln160_1_fu_948_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln160_fu_634_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_210 <= add_ln160_fu_640_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_210 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_202 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_202 <= add_ln161_fu_928_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln161_reg_1352 <= icmp_ln161_fu_654_p2;
                tmp_1_reg_1362 <= tmp_1_fu_704_p19;
                tmp_2_reg_1367 <= tmp_2_fu_736_p19;
                tmp_3_reg_1372 <= tmp_3_fu_768_p19;
                tmp_4_reg_1377 <= tmp_4_fu_800_p19;
                tmp_5_reg_1382 <= tmp_5_fu_832_p19;
                tmp_6_reg_1387 <= tmp_6_fu_864_p19;
                tmp_7_reg_1392 <= tmp_7_fu_896_p19;
                tmp_reg_1357 <= tmp_fu_672_p19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                tmp_8_reg_1397 <= tmp_8_fu_959_p19;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln160_1_fu_942_p2 <= std_logic_vector(unsigned(i_fu_206) + unsigned(ap_const_lv4_1));
    add_ln160_fu_640_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv7_1));
    add_ln161_fu_928_p2 <= std_logic_vector(unsigned(select_ln160_fu_660_p3) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln160_fu_634_p2)
    begin
        if (((icmp_ln160_fu_634_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_210, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_210;
        end if; 
    end process;


    gmem2_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            gmem2_blk_n_W <= m_axi_gmem2_0_WREADY;
        else 
            gmem2_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln160_fu_634_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv7_40) else "0";
    icmp_ln161_fu_654_p2 <= "1" when (j_fu_202 = ap_const_lv4_8) else "0";
    m_axi_gmem2_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_ARID <= ap_const_lv1_0;
    m_axi_gmem2_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_AWID <= ap_const_lv1_0;
    m_axi_gmem2_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_0_BREADY <= ap_const_logic_0;
    m_axi_gmem2_0_RREADY <= ap_const_logic_0;
    m_axi_gmem2_0_WDATA <= tmp_8_reg_1397;
    m_axi_gmem2_0_WID <= ap_const_lv1_0;
    m_axi_gmem2_0_WLAST <= ap_const_logic_0;
    m_axi_gmem2_0_WSTRB <= ap_const_lv2_3;
    m_axi_gmem2_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem2_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            m_axi_gmem2_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln160_1_fu_948_p3 <= 
        add_ln160_1_fu_942_p2 when (icmp_ln161_reg_1352(0) = '1') else 
        i_fu_206;
    select_ln160_fu_660_p3 <= 
        ap_const_lv4_0 when (icmp_ln161_fu_654_p2(0) = '1') else 
        j_fu_202;
    tmp_1_fu_704_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_2_fu_736_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_3_fu_768_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_800_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_5_fu_832_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_6_fu_864_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_7_fu_896_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_8_fu_959_p17 <= "XXXXXXXXXXXXXXXX";
    tmp_8_fu_959_p18 <= select_ln160_1_fu_948_p3(3 - 1 downto 0);
    tmp_fu_672_p17 <= "XXXXXXXXXXXXXXXX";
    trunc_ln161_fu_668_p1 <= select_ln160_fu_660_p3(3 - 1 downto 0);
end behav;
